#!/bin/sh
cat <<EOF
Content-type: text/html

<html lang="en"><head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">-->
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        
        <title>Wifi Papelaria Risque Rabisque</title>
    </head>
  
    <body>
            <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
            <a class="navbar-brand" href="https://www.facebook.com/papelariarisquerabisquenacoes/">
                <img src="/img/brand-icon-30.png" width="30" height="30" alt="">Papelaria Risque Rabisque
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarNavAltMarkup" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse show" id="navbarToggler" style="">
                <div class="navbar-nav ml-md-auto">
                    <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="#">Produtos</a>
                    <a class="nav-item nav-link" href="#">Contato</a>
                    <a class="nav-item nav-link" href="#wifi">Internet Wifi</a>
                </div>
            </div>
    </div>
        </nav>
    
    <div class="container">
        <div class="row">
            <h3 class="title">Produtos em destaque</h3>
        </div>
    <div class="row">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/img/brand.png" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
    <h5>Produto 1</h5>
    <p>R$2,89</p>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/img/brand.png" alt="Second slide"><div class="carousel-caption d-none d-md-block">
    <h5>Produto 2</h5>
    <p>Apenas R$3,90</p>
  </div>
    
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/img/brand.png" alt="Third slide"><div class="carousel-caption d-none d-md-block">
    <h5>Produto 3</h5>
    <p>Apenas R$10,99</p>
  </div>
    
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Próximo</span>
  </a>
</div>
          

</div>
</div>
        
        <div class="container">
            <div class="row">
                <h3>Internet WIFI</h3>
            </div>
            <div class="row" id="wifi">
    <p>Seu token de acesso é: </p><strong>12</strong>
    
</div>
        </div>


    <footer class="page-footer font-small blue text-center fixed-bottom">
        <div class="container">
            <div class="footer-copyright my-3">2021 MicroCap
                <a href="mailto:victor.oliveira@gmx.com"> &lt;victor.oliveira@gmx.com&gt;</a>
            </div>
        </div>
    </footer>
    
    <script src="/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/js/bootstrap.bundle.min.js"></script>
</body></html>

EOF